# Generated by Django 4.0 on 2022-01-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='national_code',
            field=models.CharField(max_length=10),
        ),
    ]
