# Generated by Django 4.0 on 2022-01-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='dasaa@sad.com', max_length=254, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
