# Generated by Django 4.0 on 2022-01-14 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(regex='[^09(1[0-9]|3[1-9]|2[1-9])-?[0-9]{3}-?[0-9]{4}]')]),
        ),
    ]
