# Generated by Django 4.0 on 2022-01-26 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_counter_customuser_phone_is_submitted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='counter',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(regex='^09\\d{9}$')]),
        ),
    ]
