# Generated by Django 4.0 on 2022-01-13 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCC', 'Succesful'), ('PROG', 'InProgress'), ('FAIL', 'Failed')], default='PROG', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCC', 'Succesful'), ('PROG', 'InProgress'), ('FAIL', 'Failed')], default='PROG', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('tax', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PEND', 'pending'), ('CANC', 'canceled')], default='PEND', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('PAID', 'Paid'), ('PEND', 'pending'), ('APPR', 'approved'), ('CANC', 'canceled')], default='PEND', max_length=4, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
