# Generated by Django 4.0 on 2022-01-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PEND', 'pending'), ('CANC', 'canceled')], default='PEND', max_length=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(blank=True, choices=[('PAID', 'Paid'), ('PEND', 'pending'), ('APPR', 'approved'), ('CANC', 'canceled')], default='PEND', max_length=4, null=True),
        ),
    ]
