# Generated by Django 4.0 on 2021-12-29 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_customer_address_customer_city_customer_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='year_in_school',
            new_name='status',
        ),
    ]
