# Generated by Django 4.0 on 2022-01-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_supplier_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
