# Generated by Django 4.0 on 2022-01-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
