# Generated by Django 4.0 on 2022-01-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_customer'),
        ('shop', '0009_alter_product_created_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
